/** Loose Diamond Worksheet — Shapes column: exact order and spellings from worksheet. */
export const diamondShapeOptions = [
  'Round',
  'Round Brilliant',
  'Single Cut',
  'Oval',
  'Oval Brilliant',
  'Heart',
  'Triangular Brilliant',
  'Triangular',
  'Square',
  'Princess',
  'Rectangular Princess',
  'Baguette',
  'Tapered Baguette',
  'Emerald',
  'Radiant',
  'Marquise',
  'Pear',
  'Square modified',
  'Cut cornered rectangular',
  'Round cornered Rectangular',
  'Cut cornered square',
  'Traiangular modified',
  'Heart modified',
  'Asscher',
  'Cushion',
  'Cushion modified',
  'Trillion',
  'Old Mine Cut',
  'Old Europian Cut'
]
