export const gemstoneEvaluationOptions = {
  shapes: [
    'Round',
    'Round Brilliant',
    'Single Cut',
    'Oval',
    'Oval Brilliant',
    'Heart',
    'Triangular Brilliant',
    'Triangular',
    'Square',
    'Princess',
    'Rectangular Princess',
    'Baguette',
    'Tapered Baguette',
    'Emerald',
    'Radiant',
    'Marquise',
    'Pear',
    'Square modified',
    'Cut cornered rectangular',
    'Round cornered Rectangular',
    'Cut cornered square',
    'Triangular modified',
    'Heart modified',
    'Asscher',
    'Cushion',
    'Cushion modified',
    'Trillion',
    'Old Mine Cut',
    'Old Europian Cut'
  ],
  cuts: [
    'Carving',
    'Bead',
    'Cabochon',
    'decorative objects',
    'Baroque',
    'Oval Mix',
    'Round',
    'Off-round',
    'Inlays',
    'Cameos',
    'Faceted',
    'Buff-top',
    'Table',
    'Intaglio',
    'Sphere',
    'Tumbled',
    'Rough',
    'Bead',
    'Rose Cut',
    'Duable Cabochon',
    'Hollow',
    'Free form',
    'Triangle',
    'Mix Cut',
    'Step cut',
    'Cushion Mix',
    'Square Step',
    'Briolette',
    'Octagonal',
    'Antique',
    'Buff Top',
    'Beads',
    'Carved'
  ],
  colours: [
    'purple',
    'reddish purple',
    'red-purple',
    'purple Red',
    'strongly purplish red',
    'slighly purplish red',
    'red',
    'orangy red',
    'red-orange',
    'orange-red',
    'reddish orange',
    'orange',
    'yellowish orange',
    'orangy yellow',
    'yellow',
    'greenish yellow',
    'yellow-green',
    'green-yellow',
    'strongly yellowish green',
    'yellowish green',
    'slighly yellowish green',
    'green',
    'very slightly bluish green',
    'bluish green',
    'very strongly bluish green',
    'green-blue',
    'blue-green',
    'very strongly greenish blue',
    'greenish blue',
    'very slightly greenish blue',
    'blue',
    'violetish blue',
    'bluish violet',
    'viole',
    'violetish purple',
    'White',
    'Black',
    'Gray',
    'Pink',
    'Brown',
    'Multi color',
    'Colorless'
  ],
  tones: [
    'very light',
    'light',
    'medium light',
    'medium',
    'medium dark',
    'dark',
    'very dark'
  ],
  transparency: [
    'Semitransparent',
    'Translucent',
    'Opaque',
    'Transparent',
    'Semitranslucent'
  ],
  phenomena: [
    'Asterism',
    'Adularescence',
    'Aventurescence',
    'Chatoyancy',
    'Color change',
    'Labradorescence',
    'Orient',
    'Iridescence',
    'Play-of-color'
  ],
  groups: [
    'Garnet',
    'Feldspar'
  ],
  // Species dropdown: exact worksheet order (131 rows; duplicates and spelling kept as in source).
  species: [
    'Corundum',
    'Zoisite',
    'Chrysoberyl',
    'Synthetic Corundum',
    'Pyrope-Spessartine',
    'Pyrope-Almandine',
    'Synthetic Chrysoberyl',
    'Rhodonite',
    'Pyrope',
    'Spodumene',
    'Andalusite',
    'Apatite',
    'Danburite',
    'Topaz',
    'Tourmaline',
    'Pezzottaite',
    'Rhodochrosite',
    'Beryl',
    'Synthetic beryl',
    'Labradorite',
    'Scapolite',
    'Quartz',
    'Synthetic Quartz',
    'Calcite',
    'Opal',
    'Synthetic Opal',
    'Glass',
    'Plastic',
    'Ruby-in-zoisite',
    'Rhodonite',
    'Unakite',
    'Hydrogrossular',
    'Jadeite',
    'Sugilite',
    'Howlite',
    'Charoite',
    'Gilson imitation coral',
    'Chalcedony',
    'Pearl',
    'Cultured pearl',
    'Calcareous concretion',
    'Shell',
    'Calcareous coral',
    'CZ (synthetic cubic zirconia)',
    'Damond',
    'Zircon',
    'Synthetic diamond',
    'GGG (gadolinium gallium garnet)',
    'YAG (yttrium aluminum garnet)',
    'Gahnite',
    'Gahnospinel',
    'Benitoite',
    'Synthetic spinel',
    'Kyanite',
    'Euclase',
    'Jeremejevite',
    'Synthetic forsterite',
    'Apatite',
    'Tourmaline',
    'Lazulite',
    'Iolite',
    'Azurmalachite',
    'Azurite',
    'Turquoise',
    'Synthetic turquoise',
    'Howlite',
    'Pectolite',
    'Chalcedony',
    'Gilson imitation lapis',
    'Microcline',
    'Magnesite',
    'Lapis lazuli',
    'Eilat stone',
    'Sodalite',
    'Sphene',
    'Andradite',
    'Uvarovite',
    'Grossularite-andradite',
    'Grossularite',
    'Epidote',
    'Idocrase',
    'Diopside',
    'Kornerupine',
    'Enstatite',
    'Peridot',
    'Andalusite',
    'Brazilianite',
    'Labradorite',
    'Azurmalachite',
    'Malachite',
    'Unakite',
    'Maw-sit-sit',
    'Hydrogrossular',
    'Saussurite',
    'Prehnite',
    'Nephrite',
    'Variscite',
    'Serpentine',
    'Aventurine',
    'Talc',
    'Spessartine',
    'Pyrope-Spessartine',
    'Axinite',
    'Sinhalite',
    'Danburite',
    'Orthoclase',
    'Pyrite',
    'Coral',
    'Serpentine',
    'Horn',
    'Tortoise shell',
    'Amber',
    'Copal resin',
    'Bone',
    'Vegetable ivory',
    'Oligoclase',
    'Ivory',
    'Ammonite',
    'Obsidian',
    'Synthetic moissanite',
    'Synthetic rutile',
    'Strontium titanate',
    'Orthoclase',
    'Alabaster',
    'Magnesite',
    'Hematite',
    'Imitation hematite',
    'Hydrogrossular',
    'Sillimanite',
    'Obsidian',
    'Jet'
  ],
  // Variety dropdown: exact worksheet order (92 rows; duplicates kept as in source).
  varieties: [
    'Spessartine',
    'Almandine',
    'Ruby',
    'Fancy Sapphire',
    'Synthetic Ruby',
    'Synthetic Fancy Sapphire',
    'Synthetic Corundum',
    'Color-Change Sapphire',
    'Synthetic Color-Change Sapphire',
    'Malaya',
    'Color-Change Garnet',
    'Rhodolite',
    'Alexandrite',
    'Synthetic Alexandrite',
    'Rhodonite (single-crystal)',
    'Pyrope',
    'Synthetic Spinel',
    'Spinel',
    'Taaffeite',
    'Tanzanite',
    'Synthetic ruby overgrowth',
    'Color-Change',
    'Synthetic Alexandrite',
    'Kunzite',
    'Parti-colored',
    'Morganite',
    'Synthetic red',
    'Synthetic morganite',
    'Red',
    'Sunstone',
    'Amethyst',
    'Ametrine',
    'Synthetic Amethyst',
    'Synthetic Ametrine',
    'Synthetic Quartz',
    'Thulite',
    'Nephrite',
    'Rose',
    'Quartzite',
    'Agate',
    'Jasper',
    'Sardonyx',
    'Sard',
    'Carnelian',
    'Onyx marble',
    'Bluejohn',
    'Sapphire',
    'Blue Sapphire',
    'Synthetic Blue sapphire',
    'Synthetic sapphire',
    'Parti-colored',
    'Aquamarine',
    'Synthetic aquamarine',
    'Chrysocolla-in-chalcedony',
    'Amazonite',
    'Onyx marble',
    'Demantoid',
    'Tsavorite',
    'Emerald',
    'Trapiche emerald',
    'Synthetic emerald',
    'Sunstone',
    'Chrysoprase',
    'Bloodstone',
    'Plasma',
    'Prase',
    'Moss agate',
    'Hessonite',
    'Heliodor',
    'Synthetic Heliodor',
    'Citrine',
    'Smoky',
    'Synthetic citrine',
    'Amber',
    'Copal resin',
    'Chiastolite',
    'Golden',
    'Tiger’s-eye',
    'Moonstone',
    'Goshenite',
    'Rock crystal',
    'Sagenitic',
    'Cat’s-eye',
    'Iceland spar',
    'Dendritic agate',
    'Onyx',
    'Mother-of-pearl',
    'Gray sapphire',
    'Cat’s-eye',
    'Black sapphire',
    'Star',
    'Onyx'
  ],
  treatments: [
    'Lattice diffusion',
    'Flux-grown',
    'Quench-crackled, dyed',
    'Dyed',
    'Polymer-impregnated',
    'Aqua aura',
    'Wax-impregnated',
    'plastic-impregnated',
    'Hpht treated',
    'Thermal Enhancement',
    'Heated',
    'Heat treated',
    'Oiling',
    'Fracture filled',
    'Quench-crackled',
    'Type B jadeite',
    'Type C jadeite',
    'Laser-drilled'
  ],
  gemstoneTypes: [
    'Natural', 'Synthetic'
  ],
  opticCharacters: [
    'SR', 'DR', 'SR/ADR', 'AGG'
  ],
  lustres: [
    'Metallic',
    'Adamantine',
    'Subadamantine',
    'Vitreous',
    'Subvitreous',
    'Greasy',
    'Resinous',
    'Waxy',
    'Dull',
    'Silky',
    'Pearly'
  ],
  // Section 6 Inclusion (Magnification): defaults first, then magnification-specific terms from worksheet.
  inclusions: [
    'two-phase inclusion',
    'three-phase inclusion',
    'cloud',
    'curved color banding',
    'curved striae',
    'Flux',
    'Fingerprint',
    'Feather',
    'Gas bubble',
    'inclusion/included',
    'Liquid',
    'Mineral',
    'Needle',
    'Negative crystal',
    'Nailhead spicule',
    'Platelet',
    'straight or angular growth',
    'Twinning',
    'uniform parallel growth',
    'Crystal',
    'fracture',
    'Cleavage',
    'Polish Lines',
    'Seed plate - hydrothermal',
    'flakes or platelets',
    'copper platelets',
    'needle-like inclusions',
    'mosaic pattern',
    'parting',
    'Conchoidal fracture'
  ],
  fluorescence: ['Very Strong', 'Strong', 'Moderate', 'Weak', 'Inert']
}

