export const gemstoneEvaluationOptions = {
  shapes: [
    'Round',
    'Round Brilliant',
    'Single Cut',
    'Oval',
    'Oval Brilliant',
    'Heart',
    'Triangular Brilliant',
    'Triangular',
    'Square',
    'Princess',
    'Rectangular Princess',
    'Baguette',
    'Tapered Baguette',
    'Emerald',
    'Radiant',
    'Marquise',
    'Pear',
    'Square modified',
    'Cut cornered rectangular',
    'Round cornered Rectangular',
    'Cut cornered square',
    'Triangular modified',
    'Heart modified',
    'Asscher',
    'Cushion',
    'Cushion modified',
    'Trillion',
    'Old Mine Cut',
    'Old Europian Cut'
  ],
  cuts: [
    'Carving',
    'Bead',
    'Cabochon',
    'decorative objects',
    'Baroque',
    'Oval Mix',
    'Round',
    'Off-round',
    'Inlays',
    'Cameos',
    'Faceted',
    'Buff-top',
    'Table',
    'Intaglio',
    'Sphere',
    'Tumbled',
    'Rough',
    'Bead',
    'Rose Cut',
    'Duable Cabochon',
    'Hollow',
    'Free form',
    'Triangle',
    'Mix Cut',
    'Step cut',
    'Cushion Mix',
    'Square Step',
    'Briolette',
    'Octagonal',
    'Antique',
    'Buff Top',
    'Beads',
    'Carved'
  ],
  colours: [
    'purple',
    'reddish purple',
    'red-purple',
    'purple Red',
    'strongly purplish red',
    'slighly purplish red',
    'red',
    'orangy red',
    'red-orange',
    'orange-red',
    'reddish orange',
    'orange',
    'yellowish orange',
    'orangy yellow',
    'yellow',
    'greenish yellow',
    'yellow-green',
    'green-yellow',
    'strongly yellowish green',
    'yellowish green',
    'slighly yellowish green',
    'green',
    'very slightly bluish green',
    'bluish green',
    'very strongly bluish green',
    'green-blue',
    'blue-green',
    'very strongly greenish blue',
    'greenish blue',
    'very slightly greenish blue',
    'blue',
    'violetish blue',
    'bluish violet',
    'viole',
    'violetish purple',
    'White',
    'Black',
    'Gray',
    'Pink',
    'Brown',
    'Multi color',
    'Colorless'
  ],
  tones: [
    'very light',
    'light',
    'medium light',
    'medium',
    'medium dark',
    'dark',
    'very dark'
  ],
  transparency: [
    'Semitransparent',
    'Translucent',
    'Opaque',
    'Transparent',
    'Semitranslucent'
  ],
  phenomena: [
    'Asterism',
    'Adularescence',
    'Aventurescence',
    'Chatoyancy',
    'Color change',
    'Labradorescence',
    'Orient',
    'Iridescence',
    'Play-of-color'
  ],
  groups: [
    'Garnet',
    'Feldspar'
  ],
  species: [
    'Corundum',
    'Zircon',
    'Synthetic Corundum',
    'Pyrope-Spessartine',
    'Pyrope-Almandine',
    'Rhodolite',
    'Pyrope',
    'Spodumene',
    'Andalusite',
    'Danburite',
    'Tourmaline',
    'Peridot',
    'Brockite',
    'Beryl',
    'Synthetic beryl',
    'Sodalite',
    'Quartz',
    'Synthetic Quartz',
    'Calcite',
    'Opal',
    'Synthetic Opal',
    'Jade',
    'Pyrophyllite',
    'Rhodonite',
    'Jadeite',
    'Sillite',
    'Howlite',
    'Coral',
    'Chalcedony',
    'Cultured pearl',
    'Seashell',
    'Carving tissue coral',
    'CZ',
    'Diamond',
    'Zircon',
    'Sillite',
    'GG (feldspar,zircon,dumortierite)',
    'Gahpite',
    'Benitoite',
    'Kyanite',
    'Beryl',
    'Euclase',
    'serpentine',
    'Aragonite forsterite',
    'Apatite',
    'Tourmaline',
    'Iolite',
    'For',
    'Aquamarine',
    'Apatite',
    'Tourquoise',
    'Synthetic turquoise',
    'Howlite',
    'Pectolite',
    'chalcedony',
    'Lapis lazuli',
    'Microline',
    'Magnisite',
    'Lep.S To Rim',
    'Sodalite',
    'Sphene',
    'Andradite',
    'Uvarovite',
    'Grossular-Andradite',
    'Grossular',
    'Eklogite',
    'Diopside',
    'Pyrope',
    'Kornerupine',
    'Feld',
    'Peridot',
    'Bixbyite',
    'Labradorite',
    'Akamalikite',
    'Zircon',
    'Unakite',
    'Ma-Wat-sit',
    'sodalite-group',
    'Pyrite',
    'Nephrite',
    'Variscite',
    'Aventurine',
    'Talc',
    'Serpentine',
    'Pyrope*Spes',
    'Asteria',
    'Sillinite',
    'Orthoclase',
    'Diorite',
    'Pyrite',
    'Coral',
    'Epiderm',
    'Horn',
    'Tissue coral',
    'Amber',
    'Coral',
    'Nephrite',
    'Log',
    'Hydrogross',
    'Coral',
    'Arbiton',
    'Howlite',
    'Synthetic turqoise',
    'Orthoclase',
    'Zoisite',
    'Alabaster',
    'Magnesite',
    'Hematite',
    'Imitation horn',
    'Hydrogrossular',
    'Sillima',
    'Sapphire',
    'Mica'
  ],
  varieties: [
    'spessartine',
    'Almandine',
    'Ruby',
    'Fancy Sapphire',
    'Synthetic Ruby',
    'Synthetic Fancy Sapphire',
    'Synthetic Corundum',
    'Color-Change Sapphire',
    'Malaya',
    'Color-Change Garnet',
    'Rhodolite',
    'Alexandrite',
    'Synthetic Alexandrite',
    'Rhodonite (single-crystal)',
    'pyrope',
    'Synthetic Spinel',
    'Spinel',
    'taaffeite',
    'Tanzanite',
    'Synthetic ruby overgrowth',
    'Color-Change',
    'Synthetic Alex',
    'Kunzite',
    'Pz1-colored',
    'Morganite',
    'synthetic red',
    'synthetic morganite',
    'Red',
    'Sunstone',
    'Amethyst',
    'Ametrine',
    'Synthetic Amethyst',
    'Synthetic Ametrine',
    'Synthetic Quartz',
    'Thulite',
    'Nephrite',
    'Rose',
    'Quartzite',
    'Agate',
    'Jasper',
    'Sardonyx',
    'Sard',
    'Carnelian',
    'Onyx marble',
    'Bluejohn',
    'Sapphire',
    'Blue Sapphire',
    'Synthetic blue sapphire',
    'Synthetic sapphire',
    'Parti-colored',
    'Aquamarine',
    'Synthetic aquamarine',
    'chrysocolla-in-chalcedony',
    'Amazonite',
    'Onyx marble',
    'Demantoid',
    'Tsavorite',
    'Emerald',
    'Trapiche emerald',
    'Synthetic emerald',
    'Sunstone',
    'chrysoprase',
    'Bloodstone',
    'Plasma',
    'pras',
    'Moss agate',
    'Hessonite',
    'Heliodor',
    'Synthetic Heliodor',
    'Citrine',
    'Smoky',
    'Synthetic citrine',
    'Amber',
    'Copper resin',
    'Chiastolite',
    'Golden',
    'Tiger’s-eye',
    'Moonstone',
    'Sogenite',
    'Rock crystal',
    'Sagenitic',
    "Cat's eye",
    'Iceland spar',
    'Dendritic agate',
    'ONYX',
    'Mother-of-pearl',
    'Gray sapphire',
    "Cat's eye",
    'Black sapphire',
    'Star',
    'ONYX'
  ],
  treatments: [
    'Lattice diffusion',
    'Flux-grown',
    'Quench-crackled, dyed',
    'Dyed',
    'Polymer-impregnated',
    'Aqua aura',
    'Wax-impregnated',
    'plastic-impregnated',
    'Hpht treated',
    'Thermal Enhancement',
    'Heated',
    'Heat treated',
    'Oiling',
    'Fracture filled',
    'Quench-crackled',
    'Type B jadeite',
    'Type C jadeite',
    'Laser-drilled'
  ],
  gemstoneTypes: [
    'Natural', 'Synthetic'
  ],
  opticCharacters: [
    'SR', 'DR', 'SR/ADR', 'AGG'
  ],
  lustres: [
    'Metallic',
    'Adamantine',
    'Subadamantine',
    'Vitreous',
    'Subvitreous',
    'Greasy',
    'Resinous',
    'Waxy',
    'Dull',
    'Silky',
    'Pearly'
  ],
  inclusions: [
    'two-phase inclusion',
    'three-phase inclusion',
    'cloud',
    'curved color banding',
    'curved striae',
    'Flux',
    'Fingerprint',
    'Feather',
    'Gas bubble',
    'inclusion/included',
    'Liquid',
    'Mineral',
    'Needle',
    'Negative crystal',
    'Nailhead spicule',
    'Platelet',
    'straight or angular growth',
    'Twinning',
    'uniform parallel growth',
    'Crystal',
    'fracture',
    'Cleavage',
    'Polish Lines'
  ],
  fluorescence: ['Very Strong', 'Strong', 'Moderate', 'Weak', 'Inert']
}

