/**
 * Jewellery subtype options (Sub Types worksheet order; duplicate entries kept as in source).
 * `value` is stored in the database; `labelAr` is shown when locale is Arabic.
 */
export const jewellerySubtypeOptions = [
  { value: 'Ring', labelAr: 'خاتم' },
  { value: 'Solitaire Ring', labelAr: 'خاتم سوليتير' },
  { value: 'Wedding Band', labelAr: 'دبلة زواج' },
  { value: 'Earrings', labelAr: 'أقراط' },
  { value: 'Pearl Earrings', labelAr: 'أقراط لؤلؤ' },
  { value: 'Diamond Studs', labelAr: 'أزرار ألماس' },
  { value: 'Precious Gemstone Earrings', labelAr: 'أقراط أحجار كريمة ثمينة' },
  { value: 'Necklace', labelAr: 'عقد' },
  { value: 'Pendant Necklace', labelAr: 'عقد مع قلادة' },
  { value: 'Diamond Necklaces', labelAr: 'عقود ألماس' },
  { value: 'Chain Necklace', labelAr: 'عقد سلسلة' },
  { value: 'Pearl Strand Necklace', labelAr: 'عقد لؤلؤ' },
  { value: 'Gemstones Strand Necklace', labelAr: 'عقد أحجار كريمة' },
  { value: 'Diamonds Strand Necklace', labelAr: 'عقد ألماس (خيوط)' },
  { value: 'Choker', labelAr: 'طوق قصير (تشوكر)' },
  { value: 'Tennis Necklace', labelAr: 'عقد تنس' },
  { value: 'Multi-Strand Necklace', labelAr: 'عقد متعدد الخيوط' },
  { value: 'Beaded Necklace', labelAr: 'عقد خرز' },
  { value: 'Beaded Bracelet', labelAr: 'سوار خرز' },
  { value: 'Diamond Bracelets', labelAr: 'أساور ألماس' },
  { value: 'Tennis Bracelets', labelAr: 'أساور تنس' },
  { value: 'Pendant', labelAr: 'قلادة' },
  { value: 'Solitaire Pendant', labelAr: 'قلادة سوليتير' },
  { value: 'Gemstone Pendant', labelAr: 'قلادة حجر كريم' },
  { value: 'Diamond Pendant', labelAr: 'قلادة ألماس' },
  { value: 'Medallion Pendant', labelAr: 'قلادة ميدالية' },
  { value: 'Locket', labelAr: 'ميدالية قلب (لوكت)' },
  { value: 'Charm (various shapes)', labelAr: 'تعليقة (أشكال متنوعة)' },
  { value: 'Charm Bracelet', labelAr: 'سوار تعليقات' },
  { value: 'Bangle', labelAr: 'أسورة صلبة' },
  { value: 'Tennis Bracelet', labelAr: 'سوار تنس' },
  { value: 'Chain Bracelet', labelAr: 'سوار سلسلة' },
  { value: 'Watch', labelAr: 'ساعة' },
  { value: 'Watch + Bracelet Sets', labelAr: 'طقم ساعة وسوار' },
  { value: 'Desk Clocks', labelAr: 'ساعات مكتب' },
  { value: 'Wall Clock', labelAr: 'ساعة حائط' },
  { value: 'Timepieces with diamonds', labelAr: 'ساعات مزينة بالألماس' },
  { value: 'Luxury Clocks', labelAr: 'ساعات فاخرة' },
  { value: 'Brooch', labelAr: 'بروش' },
  { value: 'Lapel Pin', labelAr: 'دبوس ياقة' },
  { value: 'Stick Pin', labelAr: 'دبوس عصا' },
  { value: 'Tiara / Crown/Taj', labelAr: 'تاج / تيجان' },
  { value: 'Hair Pins', labelAr: 'دبابيس شعر' },
  { value: 'Hair Clips', labelAr: 'مشابك شعر' },
  { value: 'Nose Pin', labelAr: 'دبوس أنف' },
  { value: 'Nose Ring', labelAr: 'خاتم أنف' },
  { value: 'Anklet', labelAr: 'خلخال' },
  { value: 'Toe Ring', labelAr: 'خاتم إصبع القدم' },
  { value: 'Armlet', labelAr: 'سوار ذراع' },
  { value: 'Waist Chain', labelAr: 'سلسلة خصر' },
  { value: 'Cufflinks', labelAr: 'أزرار أكمام' },
  { value: 'Tie Pin', labelAr: 'دبوس ربطة عنق' },
  { value: 'Chain', labelAr: 'سلسلة' },
  { value: 'Gold Coins', labelAr: 'عملات ذهبية' },
  { value: 'Gold Bars', labelAr: 'سبائك ذهب' },
  { value: 'Commemorative Medallions', labelAr: 'ميداليات تذكارية' },
  { value: 'Silver Coins', labelAr: 'عملات فضية' },
  { value: 'Fabergé-style Eggs', labelAr: 'بيض فابيرجيه' },
  { value: 'Ornaments', labelAr: 'زينة' },
  { value: 'Luxury Desk Ornaments', labelAr: 'زينة مكتب فاخرة' },
  { value: 'Accessories', labelAr: 'إكسسوارات' },
  { value: 'Cufflinks', labelAr: 'أزرار أكمام' },
  { value: 'Sunglasses', labelAr: 'نظارات شمسية' },
  { value: 'Pens', labelAr: 'أقلام' },
  { value: 'Lighters', labelAr: 'ولاعات' },
  { value: 'Keychains', labelAr: 'مفاتيح معلقة' },
  { value: 'Desk Accessories', labelAr: 'إكسسوارات مكتب' },
  { value: 'Vases', labelAr: 'مزهريات' },
  { value: 'Trays', labelAr: 'صواني' },
  { value: 'Tableware', labelAr: 'أدوات مائدة' },
  { value: 'Luxury Objects', labelAr: 'قطع فاخرة' },
]

export const jewellerySubtypeValues = jewellerySubtypeOptions.map((o) => o.value)

export function getJewellerySubtypeOptions(locale = 'en') {
  return jewellerySubtypeOptions.map((opt) => ({
    value: opt.value,
    label: locale === 'ar' ? opt.labelAr : opt.value,
  }))
}
